# Generated by Django 2.0.4 on 2018-04-20 14:34

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('coordinador', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Colaboradors',
                'verbose_name': 'Colaborador',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Competencias',
                'verbose_name': 'Competencia',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('nombre_corto', models.CharField(max_length=5)),
                ('color', models.CharField(choices=[('#0073b7', 'azul'), ('#39cccc', 'aqua'), ('green', 'verde'), ('#f3c612', 'amarillo'), ('#e64b55', 'rojo'), ('#605ca8', 'morado'), ('#f012be', 'rosa'), ('#ff851b', 'gris'), ('#777777', 'naranja')], default='#e64b55', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Departamentos',
                'verbose_name': 'Departamento',
            },
        ),
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicadores', to='juego.Departamento')),
            ],
            options={
                'verbose_name_plural': 'Indicadors',
                'verbose_name': 'Indicador',
            },
        ),
        migrations.CreateModel(
            name='Punteo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punteo', models.PositiveIntegerField()),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntuaciones', to='juego.Colaborador')),
                ('entregado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='juego.Colaborador')),
            ],
            options={
                'verbose_name_plural': 'Punteos',
                'verbose_name': 'Punteo',
            },
        ),
        migrations.CreateModel(
            name='Rubrica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubricas', to='juego.Indicador')),
            ],
            options={
                'verbose_name_plural': 'Rubricas',
                'verbose_name': 'Rubrica',
            },
        ),
        migrations.CreateModel(
            name='Semana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semanas', to='juego.Competencia')),
            ],
            options={
                'verbose_name_plural': 'Semanas',
                'verbose_name': 'Semana',
            },
        ),
        migrations.CreateModel(
            name='Valor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'Valors',
                'verbose_name': 'Valor',
            },
        ),
        migrations.AddField(
            model_name='rubrica',
            name='semana',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubricas', to='juego.Semana'),
        ),
        migrations.AddField(
            model_name='punteo',
            name='rubrica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punteos', to='juego.Rubrica'),
        ),
        migrations.AddField(
            model_name='indicador',
            name='valor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicadores', to='juego.Valor'),
        ),
        migrations.AddField(
            model_name='competencia',
            name='valor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='competencias', to='juego.Valor'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='colaboradores', to='juego.Departamento'),
        ),
    ]
