# Generated by Django 2.0.4 on 2018-04-20 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='punteo',
            unique_together={('colaborador', 'rubrica')},
        ),
    ]
