# Generated by Django 2.0.4 on 2018-04-20 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0002_auto_20180420_1442'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rubrica',
            unique_together={('indicador', 'semana')},
        ),
    ]
