# Generated by Django 2.0.4 on 2018-04-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0003_auto_20180420_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='punteo',
            name='porcentaje',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
