# Generated by Django 2.0.4 on 2018-05-11 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0005_auto_20180425_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='icono',
            field=models.CharField(choices=[('desktop_windows', 'PC'), ('layers', 'CAPAS'), ('local_library', 'CAPACITACIÓN'), ('map', 'MAPA'), ('apps', 'APPS'), ('sms', 'MENSAJE')], default='apps', max_length=20),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='color',
            field=models.CharField(choices=[('info', 'azul'), ('success', 'verde'), ('warning', 'amarillo'), ('danger', 'rojo'), ('primary', 'morado')], default='primary', max_length=20),
        ),
    ]
